spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URI}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

oauth:
  kakao:
    app:
      id: ${KAKAO_APP_ID}
    url:
      validation: https://kapi.kakao.com/v1/user/access_token_info
      user: https://kapi.kakao.com/v2/user/me

naver:
  apiKeyId: ${X-NCP-APIGW-API-KEY-ID}
  apiKey: ${X-NCP-APIGW-API-KEY}

jwt:
  secret: ${JWT_SECRET_KEY}
  # 10일
  access-token-time: 864000000
  # 30일
  refresh-token-time: 2592000000

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /api/docs
  api-docs:
    path: /api/docs

cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}


