server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URI}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

